---
# SSH keys to deploy (override them in host_vars if ever necessary)
# The files refer to files in the common role
ssh_users:
  - zeridon
  - maniax
  - arcopix
  - hackman
  - lz1irq
  - shteryana
  - tochev
  - Yasen6275

timezone: "Europe/Sofia"

ntp:
  server:
    - marla.ludost.net
  pool:
    - 0.bg.pool.ntp.org
